Repository ManageIQ/manageiq-providers-azure_stack, pull requests merged in 2019-10, with the labels that each got.

#12 NetworkManager parser sets resource group for networks, network ports and security groups
  app/models/manageiq/providers/azure_stack/inventory/parser/network_manager.rb
  app/models/manageiq/providers/azure_stack/inventory/persister/definitions/network_collections.rb
  spec/models/manageiq/providers/azure_stack/cloud_manager/vcr_specs/refresher_spec.rb
Labels: enhancement

#14 Add methods for for provider creation pluggable UI
  app/models/manageiq/providers/azure_stack/manager_mixin.rb
Labels: enhancement

#15 Targeted refresh for ResourceGroup
  app/models/manageiq/providers/azure_stack/ems_ref_mixin.rb
  app/models/manageiq/providers/azure_stack/inventory.rb
  app/models/manageiq/providers/azure_stack/inventory/collector.rb
  app/models/manageiq/providers/azure_stack/inventory/collector/target_collection.rb
  app/models/manageiq/providers/azure_stack/inventory/collector/target_collection/v2017_03_09.rb
  app/models/manageiq/providers/azure_stack/inventory/collector/target_collection/v2018_03_01.rb
  app/models/manageiq/providers/azure_stack/inventory/persister.rb
  app/models/manageiq/providers/azure_stack/inventory/persister/definitions/cloud_collections.rb
  app/models/manageiq/providers/azure_stack/inventory/persister/definitions/network_collections.rb
  app/models/manageiq/providers/azure_stack/inventory/persister/target_collection.rb
  config/settings.yml
  spec/factories/cloud_network.rb
  spec/factories/network_port.rb
  spec/factories/resource_group.rb
  spec/factories/security_group.rb
  spec/models/manageiq/providers/azure_stack/cloud_manager/vcr_specs/targeted_refresh_spec.rb
  spec/vcr_cassettes/manageiq/providers/azure_stack/cloud_manager/refresher_targeted/V2017_03_09-resource_group.yml
  spec/vcr_cassettes/manageiq/providers/azure_stack/cloud_manager/refresher_targeted/V2017_03_09-resource_group_deleted.yml
  spec/vcr_cassettes/manageiq/providers/azure_stack/cloud_manager/refresher_targeted/V2018_03_01-resource_group.yml
  spec/vcr_cassettes/manageiq/providers/azure_stack/cloud_manager/refresher_targeted/V2018_03_01-resource_group_deleted.yml
Labels: enhancement

#16 Events to refresh resource group target
  app/models/manageiq/providers/azure_stack/cloud_manager/event_target_parser.rb
  spec/models/manageiq/providers/azure_stack/cloud_manager/event_target_parser_spec.rb
Labels: enhancement

#17 Rename event source from AZURE_STACK to AZURESTACK
  app/models/manageiq/providers/azure_stack/cloud_manager/event_parser.rb
  spec/models/manageiq/providers/azure_stack/cloud_manager/event_catcher/runner_spec.rb
  spec/models/manageiq/providers/azure_stack/cloud_manager/event_parser_spec.rb
  spec/models/manageiq/providers/azure_stack/cloud_manager/vcr_specs/event_stream_spec.rb
Labels: refactoring

#18 Test ruby 2.5.7/2.6.5, see: ManageIQ/manageiq#19414
  .travis.yml
Labels: test
