Repository ManageIQ/manageiq-providers-azure_stack, pull requests merged in 2020-05, with the labels that each got.

#30 Fix event_target_parser spec
  app/models/manageiq/providers/azure_stack/cloud_manager/event_parser.rb
  spec/models/manageiq/providers/azure_stack/cloud_manager/event_target_parser_spec.rb
Labels: bug, test

#26 Adjusted DDF schema and validation
  app/models/manageiq/providers/azure_stack/manager_mixin.rb
Labels: enhancement

#29 Added proper channel to code climate config file
  .codeclimate.yml
Labels: bug, developer

#31 Fix README to point to travis-ci.com instead of travis-ci.org
  README.md
Labels: bug, developer

#32 Removing deprecated Gemnasium badge
  README.md
Labels: developer
