Repository ManageIQ/manageiq-providers-azure_stack, pull requests merged in 2020-10, with the labels that each got.

#40 Test with ruby 2.5.8 and 2.6.6
  .travis.yml
Labels: test

#41 Use manageiq-style
  .codeclimate.yml
  .rubocop.yml
  .rubocop_cc.yml
  manageiq-providers-azure_stack.gemspec
Labels: developer, enhancement

#42 Fix .rubocop_local.yml
  .rubocop_local.yml
Labels: developer
