Repository ManageIQ/manageiq-providers-azure_stack, pull requests merged in 2021-04, with the labels that each got.

#61 Use pluggable provider secrets for vcr specs
  config/secrets.defaults.yml
  lib/manageiq/providers/azure_stack/engine.rb
  spec/factories/ext_management_system.rb
  spec/models/manageiq/providers/azure_stack/cloud_manager/vcr_specs/cloud_manager_spec.rb
  spec/models/manageiq/providers/azure_stack/cloud_manager/vcr_specs/event_stream_spec.rb
  spec/models/manageiq/providers/azure_stack/cloud_manager/vcr_specs/refresher_spec.rb
  spec/models/manageiq/providers/azure_stack/cloud_manager/vcr_specs/targeted_refresh_spec.rb
  spec/spec_helper.rb
Labels: refactoring, test

#54 convert regexp event detection to strings
  config/settings.yml
Labels: enhancement

#63 ResourceGroups should live under the CloudManager
  app/models/manageiq/providers/azure_stack/cloud_manager.rb
  app/models/manageiq/providers/azure_stack/cloud_manager/resource_group.rb
  app/models/manageiq/providers/azure_stack/resource_group.rb
  spec/factories/resource_group.rb
Labels: technical debt
